import {
  LucideActivity,
  LucideAlertCircle,
  LucideArrowRight,
  LucideCheck,
  LucideChevronDown,
  LucideCircleCheck,
  LucideCircleX,
  LucideCode,
  LucideCommand,
  LucideCpu,
  LucideExternalLink,
  LucideFileText,
  LucideHome,
  LucideInfo,
  LucideLoaderCircle,
  LucideMoon,
  LucidePlay,
  LucidePlus,
  LucideSearch,
  LucideSettings,
  LucideSparkles,
  LucideSun,
  LucideTrash2,
  LucideUpload,
  LucideX,
} from '@lucide/angular';

export const NEURAL_LUCIDE_ICONS = [
  LucideActivity,
  LucideAlertCircle,
  LucideArrowRight,
  LucideCheck,
  LucideChevronDown,
  LucideCircleCheck,
  LucideCircleX,
  LucideCode,
  LucideCommand,
  LucideCpu,
  LucideExternalLink,
  LucideFileText,
  LucideHome,
  LucideInfo,
  LucideLoaderCircle,
  LucideMoon,
  LucidePlay,
  LucidePlus,
  LucideSearch,
  LucideSettings,
  LucideSparkles,
  LucideSun,
  LucideTrash2,
  LucideUpload,
  LucideX,
] as const;

export const NEURAL_LUCIDE_ICON_NAMES = [
  'activity',
  'alert-circle',
  'arrow-right',
  'check',
  'chevron-down',
  'circle-check',
  'circle-x',
  'code',
  'command',
  'cpu',
  'external-link',
  'file-text',
  'home',
  'info',
  'loader-circle',
  'moon',
  'play',
  'plus',
  'search',
  'settings',
  'sparkles',
  'sun',
  'trash-2',
  'upload',
  'x',
] as const;
